 version: '3.8'

services:
  data_ingestion:
    build:
      context: ./data_ingestion
      dockerfile: Dockerfile
    volumes:
      - ./data:/data  # Adjust according to your data directory
    command:  python dataloader.py

  preprocessing:
    build:
      context: ./data_preprocessing
      dockerfile: Dockerfile
    depends_on:
      - data_ingestion
    volumes:
      - ./data:/data  # Ensure the data is shared
    command:  python preprocess_cv.py

  # Uncomment and adjust for the rag service if needed
  # rag:
  #   build:
  #     context: ./ag
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - preprocessing
  #   volumes:
  #     - ./data:/data  # Ensure the data is shared
  #   command: ["bash", "-c", "source .venv/bin/activate && exec python rag.py"]