version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: cadcoder-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: .
    container_name: cadcoder-backend
    env_file: .env               #Load backend environment automatically
    ports:
      - "8000:8000"
    volumes:
      - ./secrets:/app/secrets
    depends_on:
      - mongo
    restart: always

  # Optional pipeline services (run on demand)
  ingestion:
    build: ../src/datapipeline/data_ingestion
    container_name: cadcoder-ingestion
    env_file: .env
    volumes:
      - ../data:/app/data
    command: ["python", "dataloader.py"]

  preprocess:
    build: ../src/datapipeline/data_preprocessing
    container_name: cadcoder-preprocess
    env_file: .env
    volumes:
      - ../data:/app/data
    command: ["python", "preprocess_cv.py"]

  rag:
    build: ../src/datapipeline/rag
    container_name: cadcoder-rag
    env_file: .env
    volumes:
      - ../data:/app/data
    command: ["python", "pipeline.py"]

volumes:
  mongo_data:
